### ISSUE TITLE
bar chart - Mukund

### ISSUE THREAD

**Issue by MacyChan** [UBC-MDS/world-energy-visualization#13]

**Comment by MacyChan** [comment]
A few issue needa be fixed.
1. For bottom, the number of chart does not match the selection. 
2. Some bars are showing with numbers 3. 
3. As shown in the images, bottm 6 & 7 are showing different countries.

![image](https://user-images.githubusercontent.com/74348088/156702455-3fe6005d-58a8-478d-aaa1-790c26eeafcf.png)
![image](https://user-images.githubusercontent.com/74348088/156702471-67c2527c-ec75-4696-a1cc-62a186412fde.png)

**Comment by miyer26** [comment]
I will check on these issues

**Comment by miyer26** [comment]
Sorry for my oversight, the issues should be fixed now. Please do take a look. As Pavel had mentioned, I have also removed the zoom on scroll feature on the world map to make it easier to navigate the app.
